repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        verbose: true
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        verbose: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        verbose: true
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        verbose: true
        args:
          [
            "--score=no",
            "--signature-mutators=validator_with_transform,on_sqs_message",
          ]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--strict]
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        args: ["-rqs", "B101,B404,B603,B311"]
